# Generated by Django 3.2.3 on 2021-05-13 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarWash',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('licensePlate', models.CharField(blank=True, max_length=50, null=True)),
                ('vehicleType', models.CharField(blank=True, max_length=50, null=True)),
                ('created_date', models.DateTimeField()),
                ('amountPaid', models.IntegerField(blank=True, default='0', null=True)),
            ],
        ),
    ]
