# Generated by Django 3.2.3 on 2021-05-13 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(blank=True, max_length=50, null=True)),
                ('category', models.CharField(blank=True, max_length=50, null=True)),
                ('pieces', models.IntegerField(blank=True, default='0', null=True)),
                ('quantity', models.IntegerField(blank=True, default='0', null=True)),
                ('unitPrice', models.IntegerField(blank=True, default='0', null=True)),
            ],
        ),
    ]
