# Generated by Django 3.2.3 on 2021-05-13 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stockmgmt', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='quantity',
        ),
    ]
