# Generated by Django 3.2.3 on 2021-05-13 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockmgmt', '0002_remove_stock_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='unitPrice',
            field=models.FloatField(blank=True, default='0', null=True),
        ),
    ]
